### ISSUE TITLE
Issue with stock buy in GBp

### ISSUE THREAD

**Issue by pvieira84** [VibeNL/GhostfolioSidekick#128]
I have one activity (DEGIRO PT) being imported with the incorrect unit price. My file has 235 GBp (pence) but when the activity is created, the Unit Price is saved as 23500 GBp

Activity price:
<img width="579" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/76f1e589-5f74-4c55-8fa0-c5d117489d5f">

Import file:
<img width="666" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/83c34150-7774-4fb5-8abb-97cce3494a0d">

Config file:
<img width="111" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/c22c8cd9-48c7-4025-90af-a925b3983465">

Exchange Rates:
<img width="111" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/69ee3546-ef1f-4f3a-897e-c29c59618fbf">

**Comment by VibeNL** [comment]
Seems like a bug. Will have a look at it next week 😅.

**Comment by VibeNL** [comment]
@pvieira84 , I have changed some code ( see https://github.com/VibeNL/GhostfolioSidekick/pull/136). If you could verify that version, that would be great

**Comment by pvieira84** [comment]
@VibeNL I can confirm #136 fixed my issue. Thanks

**Comment by VibeNL** [comment]
Your welcome 😁
