### ISSUE TITLE
Trading 212 support

### ISSUE THREAD

**Issue by pvieira84** [VibeNL/GhostfolioSidekick#160]
I am having some errors logged with T212 while in the past it was working perfectly.

My export has the below headers and it contains Deposits, Market Buys, Market Sells and Withdrawals:
"Action,Time,ISIN,Ticker,Name,No. of shares,Price / share,Currency (Price / share),Exchange rate,Result,Currency (Result),Total,Currency (Total),Finra fee,Notes,ID,Currency (Finra fee)"

However, looking at our test files for T212 parser, it seems that the headers are different from mine. It also seems that the header varies depending on what type of transactions we are dealing with.

So, is there anything else specific I need to do when exporting the transaction history from T212?

Here are the errors logged:
<img width="1292" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/5f2c2e6d-792b-4789-a8b8-9ecb2e2a641d">

**Comment by pvieira84** [comment]
@VibeNL I gave it a go with pr-162 but then all the transactions on accounts I was managing manually without the sidekick got deleted.

Here's one example file:
[t212_2024_example.csv](https://github.com/VibeNL/GhostfolioSidekick/files/14322303/t212_2024_example.csv)

**Comment by VibeNL** [comment]
Hmmm, sounds like an unrelated bug. Did the imported row themselves seem correct?

I'll have a look on why it is updating accounts it shouldn't

**Comment by pvieira84** [comment]
Import seems ok

**Comment by VibeNL** [comment]
I updated the code to only update accounts that have a transaction provided from one of the importfiles.

**Comment by pvieira84** [comment]
Seems to be working now

**Comment by VibeNL** [comment]
Closing this issue 😀.

In case there are any other issues, let me know.
