### ISSUE TITLE
Trading212 - Wrong ticker being used

### ISSUE THREAD

**Issue by pvieira84** [VibeNL/GhostfolioSidekick#176]
So I have bought some shares of ISIN IE00B4L5Y983 which has different tickers depending for example on the Exchange/Currency.

In my t212 file, I have this:
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/98585914-8d19-45df-bda2-564ec7efb776)

The ticker is EUNL. But sidekick is using a different ticker:
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/3ac1662d-f60e-4cc7-b94a-4dadae4faed6)

I tried to used the config file to change this but none of the below additions worked for me
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/8c9dfc45-cee4-461c-a902-89af08e2d576)
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/d5064c1c-5f51-43d2-a701-def6eb90e4a7)

Can you shed some light on how can I get these activities imported with ticker EUNL.DE?

**Comment by VibeNL** [comment]
To help I have added some logging in the latest version of the container

**Comment by pvieira84** [comment]
So I've followed the steps and what happened was that the app updated the comment to what it was again i.e. "Known Identifiers: [IE00B4L5Y983]"

Then I tried a different approach and the result was different as well.

- deleted the activities
- deleted the symbol from Market Data
- recreated the container

It now created the activities associated with ticker IWDA.L - this is what I have in the logs:
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/ca2e9db2-d9ff-46d4-b1b8-b2f710039879)
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/1987f79e-4a08-4b39-91ce-73d0fc84202c)
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/25412a0a-85a2-4b49-b59f-20a4b7e46aaf)

This is my current config:
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/cb2cef33-6eb5-422b-8f2a-23c10fa53a2e)

**Comment by VibeNL** [comment]
I can see from the first screenshot that your config file is not being read 'mappings #0'

Could you check the path to the config is being set correctly?

**Comment by pvieira84** [comment]
This is what I have set. It's in the same folder of the import files
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/f539a6b3-33a0-4ddc-9110-b8259c34ee54)

**Comment by VibeNL** [comment]
That looks correct 👍🏻. just to rule it out (if you are running Linux), is the casing correct?

**Comment by pvieira84** [comment]
it is:
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/be1bd581-5a97-49a6-a3b7-0b6ad50bc75f)

**Comment by VibeNL** [comment]
I was afraid of that. Will add some extra logging   in the coming weeks to try to explain what is going wrong 😅

**Comment by VibeNL** [comment]
Created a pull request for the logging, the first statement I added should at least confirm that the default config is used. Could you install that version and share the log?

**Comment by pvieira84** [comment]
Well, your PR helped me find the issue.

Logs:
2024-03-08T08:55:41.190483278Z warn: GhostfolioSidekick.Configuration.ApplicationSettings[0]
2024-03-08T08:55:41.190523769Z       No (valid) configuration file found at /import/config.json. Using default configuration.. Error was '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.settings | LineNumber: 6 | BytePositionInLine: 2.

It happens that my json was not valid :S
A comma was missing
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/7e40941b-ee0c-4a04-9456-5545d6d4c8c0)

After fixing the JSON:
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/09ee2294-5c8b-4381-a62b-3c88e2992c93)
and
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/6477a764-1357-470f-9a12-a9efd9538bd6)

There's still an issue though - before testing I deleted the activities pointing to the wrong ticker but now even though the mapping is correctly identified, the activities are not getting imported at all (for my mapped EUNL ticker) . I have a couple of these fails in the logs, don't know if it means something
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/1fdc9381-db4a-4243-baf8-5ecf94c88b64)

**Comment by VibeNL** [comment]
Glad to hear you have found the issue. 

Regarding the other issue, I may have broken something with the last refactoring. Hopefully the new master it is fixed. If not, could you please open a new ticket :)?
