### ISSUE TITLE
All fees are imported at each execution

### ISSUE THREAD

**Issue by pvieira84** [VibeNL/GhostfolioSidekick#180]
As the title says - apparently there's currently no check if the fee already exists

Logs:
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/95fbc50c-c030-48df-9f06-cea8f50bd422)
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/88a51e49-876a-4a2f-938d-ac797572734f)

**Comment by VibeNL** [comment]
I see, there is a comparison, but apparently it's broken 😇. I have the same issue in my dataset.

**Comment by VibeNL** [comment]
Just updated the main version of ghostfolio (commit #819). Let me know if it helped :)

**Comment by pvieira84** [comment]
Thanks for the quick reply - seems to be working now
