### ISSUE TITLE
Delete unused symbols is deleting Fear & Greed Index

### ISSUE THREAD

**Issue by pvieira84** [VibeNL/GhostfolioSidekick#182]
Setting "delete.unused.symbols"=true deletes symbol "_GF_FEAR_AND_GREED_INDEX" (see https://github.com/ghostfolio/ghostfolio/discussions/833)

**Comment by VibeNL** [comment]
Never heard of this 😇, undocumented features are the greatest 🤭. Will have a look at it when I have the time. 

For now, disabling the feature should work as a workaround 😅.

**Comment by VibeNL** [comment]
It should be fixed in the latest version.

**Comment by VibeNL** [comment]
@pvieira84 , can you verify if it is fixed in the latest version?
