### ISSUE TITLE
Coinbase - datetime conversion issue

### ISSUE THREAD

**Issue by pvieira84** [VibeNL/GhostfolioSidekick#190]
I'm having the following conversion issue for Coinbase
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/754ed081-cfcb-4644-82a1-507ffda9a3ea)

Seems that the format I'm getting while exporting from Coinbase is different from what you have in your unit tests (https://github.com/VibeNL/GhostfolioSidekick/blob/master/Parsers.UnitTests/TestFiles/Coinbase/BuyOrders/single_buy.csv)
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/9a7a67cf-6e2f-4059-9b71-2be29d37ed92)

This is what I have in my file:
![image](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/60d491d7-debd-4f44-8a6b-dc544b3dc406)

I'm exporting from here: https://accounts.coinbase.com/statements

**Comment by VibeNL** [comment]
To correctly implement could you provide a few example files (with fabricated data if you so please). I see also a buy type I haven't seen 😇

**Comment by pvieira84** [comment]
I've added a few different dummy transactions to the attached file - thanks for your support
[dummy_transactions_history.csv](https://github.com/VibeNL/GhostfolioSidekick/files/14638672/dummy_transactions_history.csv)

**Comment by VibeNL** [comment]
I have edited some code, could you test the build at the pull request?

**Comment by pvieira84** [comment]
I can see some buy and sells activities being imported successfully but for example the learning rewards are not being imported.
I have this error in the logs - can't tell which entry is causing it :|
<img width="705" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/6335e8a2-e48d-472a-98ee-c876d3b80698">

**Comment by VibeNL** [comment]
Hmmm, just exported my own history and apparently they have updated their export format. I'm in the process of updating the parser 😇

**Comment by VibeNL** [comment]
Making some progress, still having some issues  with conversions of assets

**Comment by VibeNL** [comment]
Good to hear it is working, closing the pull request :). If there are still any issues, please raise a new issue.
