### ISSUE TITLE
Dust workaround

### ISSUE THREAD

**Issue by pvieira84** [VibeNL/GhostfolioSidekick#196]
I have enabled the dust workaround:
<img width="334" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/f839e06e-fd14-47c2-b832-af8f47e1f71c">

I have the following activities for a specific cryptocurrency:
<img width="137" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/8132ef46-3992-4853-a152-974b6736e2aa">

But apparently the dust workaround is not working because the holding is still showing up in ghostfolio with quantity 0 and value 0. Is my understanding correct that the DUST should be zero when the workaround is enabled?
<img width="308" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/ad0ad0e7-1906-46ee-8509-c6c47853b073">

**Comment by VibeNL** [comment]
Yes, it should get the total to 0, however it is experimental and apparently broken 😇.

Will put it on the todo list.

**Comment by VibeNL** [comment]
@pvieira84 , I have edited some code, if you are feeling brave you can try it. Haven't had the time to test it thoroughly, but it appears to make it a bit better.

**Comment by pvieira84** [comment]
@VibeNL should I go ahead and test it or are you still doing adjustments?

**Comment by pvieira84** [comment]
Here are the results of my tests. I had around 15 crypto coins with dust and +/- 10 of them were correctly zeroed however the following cryptos were correct before and are now incorrect. On the left you can see the activities before your fix and on the right the activities after your fix.
<img width="920" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/ff731211-ee59-4498-b7de-cccdd8286cb1">

**Comment by VibeNL** [comment]
hmm, I'll have a look 😢

**Comment by VibeNL** [comment]
Just to be sure, can you share your config file (or at least the settings configuration)?

**Comment by pvieira84** [comment]
Here you go: ![Screenshot_20240415-193058](https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/5864032a-55ec-4e54-9923-ca15ba818ef6)

**Comment by VibeNL** [comment]
Could you give it another go?

I currently have some issues with my installation 😅

**Comment by pvieira84** [comment]
Magic :)

<img width="582" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/89975028/07ab6873-e8ea-4d9d-aa2b-cf09e349afc0">

**Comment by VibeNL** [comment]
All green 💚, merging it to master 😇
