### ISSUE TITLE
Scalable Capital: CSV format changed

### ISSUE THREAD

**Issue by mp68** [VibeNL/GhostfolioSidekick#201]
It appears that the CSV format from Scalable Capital has changed. It now looks like this (sample data):

| date     | time     | status   | reference | description                | assetType | type         | isin         | shares | price | amount  | fee  | tax | currency |
| -------- | -------- | -------- | --------- | -------------------------- | --------- | ------------ | ------------ | ------ | ----- | ------- | ---- | --- | -------- |
| 1980-01-01 | 12:00:00 | Executed | abcde     | Microsoft Corp             | Security  | Buy          | US5949181045 | 100    | 100,23   | \-10000 | 0,99 | 0   | EUR      |
| 1980-01-02 | 12:00:00 | Executed | abcde     | Scalable Capital           | Cash      | Deposit      |              |        |       | 2500    | 0    |     | EUR      |
| 1980-10-01 | 13:24:00 | Executed | abcde     | Microsoft Corp             | Cash      | Distribution | US5949181045 |     |   | 950   | 0       |      | EUR |
| 2024-01-01 | 10:43:07 | Executed | abcde     | Xtrackers MSCI World (Acc) | Security  | Savings plan | IE00BJ0KDQ92 | 100    | 50,11    | \-5.000 | 0    | 0   | EUR      |

**Comment by VibeNL** [comment]
Thanks for the heads up 👍🏻, will have a look at it when I have the time.

**Comment by VibeNL** [comment]
Would you be so kind to please provide a bit more information. Scalable Capital export used to consist of 2 sets of files, in your example only one would be sufficient: which type has changed 😅?

Or is this a new type of export that I haven't found yet, if so could you provide how to do the export?

**Comment by mp68** [comment]
Thank you for looking into this! I'm very happy to provide more info. Apparently, Scalable Capital changed their export format. The old format is no longer available via Baader or the Scalable Capital interface. 
The new file can be exported through the web broker via the transactions page. You will have to select the transactions of interest or all transactions and the a button for CSV export is provided. I hope this helps! 
<img width="637" alt="image" src="https://github.com/VibeNL/GhostfolioSidekick/assets/10088505/6c39b46e-515e-435d-9b45-5ad4f8468a26">

**Comment by VibeNL** [comment]
Hmmm, it is a premium feature. Could you create a CSV file with the table you mentioned before. I can then implement a parser for it 😇

**Comment by mp68** [comment]
Sure! I created a CSV file with sample data 😊
The field "reference" appears to be unique. I guess this could be used for duplicate detection.
[Scalable Capital sample file.csv](https://github.com/VibeNL/GhostfolioSidekick/files/14898003/Scalable.Capital.sample.file.csv)

**Comment by mp68** [comment]
Works great! All positions were correctly imported! Thank you for your great work 👍

**Comment by VibeNL** [comment]
You're welcome
