### ISSUE TITLE
Help in running docker instance

### ISSUE THREAD

**Issue by huub66** [VibeNL/GhostfolioSidekick#242]
What is the status of this application? Looks like potentially a great application, thanks for the effort!
I'm struggling to get the docker container running, could you share an instruction on how to initiate the docker instance either via commandline or compose file?

**Comment by VibeNL** [comment]
Hey @huub66 ,

The application should be running fine :)

Can you take a look at https://github.com/VibeNL/GhostfolioSidekick/issues/129, there is something similar and includes the compose file.

Let me know if you need further assistance.

Kind regards

**Comment by huub66** [comment]
Great, thanks for the pointer. Application is running!

**Comment by huub66** [comment]
Great, thanks for the pointer. Application is running!
