### ISSUE TITLE
fixing culture changes breaking tests

### ISSUE THREAD

**Issue by Joren-vanGoethem** [VibeNL/GhostfolioSidekick#50]
we need a way to fix the culture difference breaking the tests.

either by detecting culture and adjusting accordingly or finding a way to parse the data culture-invariant

**Comment by VibeNL** [comment]
Invariant culture would be my preferred way, dates are only used for tracking records.

**Comment by VibeNL** [comment]
@Joren-vanGoethem , could you review the PR?

**Comment by VibeNL** [comment]
Completed the PR. please let me know if there is still a problem 👼
