### ISSUE TITLE
Allow multiple file types for one account

### ISSUE THREAD

**Issue by VibeNL** [VibeNL/GhostfolioSidekick#63]
Currently only a single parser can handle an account. It would be nice to support multiple formats for an account.

Usecases:
 - Export formats of brokers can change, we should be able to keep using the ealier exported files
 - Some brokers can export multiple file types, we should have the option to mix and match
 - We should be able to use the generic import format in combination with the export from a broker when the export functionality is (temporary) not available.

**Comment by Joren-vanGoethem** [comment]
what do you mean exactly? like a json and a csv parser that can both add items to the same account?

**Comment by VibeNL** [comment]
I updated the decription, please let me know if it is still unclear with my intention.
