### ISSUE TITLE
Inconsistent Symbol detection

### ISSUE THREAD

**Issue by jdcmarques** [VibeNL/GhostfolioSidekick#68]
Having a weird issue parsing some transactions from trading 212.

If I restart the container I get new errors saying that XXX symbol was not found

One run
```
info: GhostfolioSidekick.FileImporter.FileImporterTask[0]
      AccountName: Trading 212
fail: GhostfolioSidekick.Ghostfolio.API.GhostfolioAPI[0]
      Could not find HEIA.AS as a symbol
fail: GhostfolioSidekick.Ghostfolio.API.GhostfolioAPI[0]
      Could not find IE00B3XXRP09 as a symbol
fail: GhostfolioSidekick.Ghostfolio.API.GhostfolioAPI[0]
      Could not find US0079031078 as a symbol
```
Second run
```
info: GhostfolioSidekick.FileImporter.FileImporterTask[0]
      AccountName: Trading 212
fail: GhostfolioSidekick.Ghostfolio.API.GhostfolioAPI[0]
      Could not find VWCE.DE as a symbol
fail: GhostfolioSidekick.Ghostfolio.API.GhostfolioAPI[0]
      Could not find US02079K3059 as a symbol
fail: GhostfolioSidekick.Ghostfolio.API.GhostfolioAPI[0]
      Could not find US0231351067 as a symbol
```

Would this be an issue with Ghostfolio getting limited on the API?

**Comment by VibeNL** [comment]
Indeed, possibly a throttling issue. 

The symbol information is being read from Ghostfolio and stored in a memory cache for 24 hours. However on restart there is no cache yet.

Do the errors eventually disappear?

I myself haven't encountered the problem so any additional information would be nice (amount of symbols, number of transactions)

**Comment by jdcmarques** [comment]
Left if it on for a while it eventually sorted itself out and added all symbols to it.

Got 314 transactions with 26 symbols.

The funny problem is that when sidekick gets restarted Ghostfolio should already have the old ticker on it, unless it bypasses directly to fetch from Yahoo finance
