### ISSUE TITLE
Degiro Parser

### ISSUE THREAD

**Issue by jdcmarques** [VibeNL/GhostfolioSidekick#83]
Can you share the CSV Header format for Degiro?
I use degiro.pt and the export format is not compatible with the current implementation, this is what I have currently.
Data,Hora,Produto,ISIN,Bolsa de,Bolsa,Quantidade,Preços,,Valor local,,Valor,,Taxa de Câmbio,Custos de transação,,Total,,ID da Ordem

**Comment by VibeNL** [comment]
Apparently DeGiro exports in the local language. You can find the files I use in the repository, for example: https://github.com/VibeNL/GhostfolioSidekick/blob/master/GhostfolioSidekick.UnitTests%2FFileImporter%2FTestFiles%2FDeGiro%2FBuyOrders%2Fsingle_buy_euro.csv

If you can translate the headers for me to English we could add support for your files 😅. Or add a PR request yourself if that is an option

**Comment by VibeNL** [comment]
And some example files would be great 👍

**Comment by jdcmarques** [comment]
I can try an open up a PR. Never used dotnet, but should be doable 😂

**Comment by jdcmarques** [comment]
Example CSV

```csv
Data,Hora,Produto,ISIN,Bolsa de,Bolsa,Quantidade,Preços,,Valor local,,Valor,,Taxa de Câmbio,Custos de transação,,Total,,ID da Ordem
31-01-2022,08:00,ISHARES NASDAQ 100 UCITS ETF EUR HEDGED ACC,IE00BYVQ9F29,TDG,XGAT,2,9.2660,EUR,-18.53,EUR,-18.53,EUR,,-3.90,EUR,-22.43,EUR,332c137b-bc1a-4cff-9aff-cb5728ed9874
15-11-2021,15:49,ISHARES EM MARKETS,IE00B0M63177,EAM,XAMS,-2,43.6350,EUR,87.27,EUR,87.27,EUR,,,EUR,87.27,EUR,ecc6974b-effa-48c6-96d9-e05ab921d90f
```

**Comment by VibeNL** [comment]
> I can try an open up a PR. Never used dotnet, but should be doable 😂 

Give it a go, otherwise I'll have a look in the new year.

**Comment by VibeNL** [comment]
@jdcmarques, I have had a look and you have exported the transaction history instead of the account history. I have started a branch to add support for this as well.

**Comment by VibeNL** [comment]
Just to check, the language is Portuguese?

**Comment by jdcmarques** [comment]
Yes it's Portuguese.

Will check it I have dividend transactions. Don't think so

**Comment by jdcmarques** [comment]
Anyway I can share with you the CSV besides GH Issues?

**Comment by VibeNL** [comment]
Will give it a go in the coming weeks 😁

**Comment by VibeNL** [comment]
@jdcmarques , I made a small start to parse your file, can you verify if https://github.com/VibeNL/GhostfolioSidekick/pull/95/files#diff-3ae8dba0f84754e9119da678f5265b6921a392ce64c77f0d902576839e93559b makes any sense 👼 ?

**Comment by jdcmarques** [comment]
Everything looks great!

Think only this is missing, this is Degiro fee for connection to an exchange, should it be included in the isFree function as well? 
```
03-01-2023,14:06,31-12-2022,,,Custo de Conectividade DEGIRO 2023 (Xetra - XET),,EUR,-2.50,EUR,107.18,
```

**Comment by VibeNL** [comment]
Those should be added as a Fee activity I think, see GetActivityType().

**Comment by VibeNL** [comment]
Merge the PR as a first version, let me know if any changes are needed

**Comment by jdcmarques** [comment]
Worked great, just came to check all transactions, thanks a lot!

**Comment by VibeNL** [comment]
Your welcome 👍
